### ISSUE TITLE
Actions运行  提示这样，求教

### ISSUE THREAD

**Issue by BSZC** [lqkxs3608/daily_signin#1]
Run python3 index.py
  python3 index.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.8/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.8/x64/lib
    QYWX_CORPID: ***
    QYWX_CORPSECRET: ***
    QYWX_AGENTID: ***
    PJ_COOKIE: ***
    CSDN_COOKIE: ***
    TYYP_USERNAME: 
    TYYP_PSW: ***
    TOOLLU_COOKIE: ***
Traceback (most recent call last):
  File "index.py", line 44, in <module>
    notify.send(toollu_msg)
TypeError: send() missing 1 required positional argument: 'text'
Error: Process completed with exit code 1.

**Comment by lqkxs3608** [comment]
> Run python3 index.py
> python3 index.py
> shell: /usr/bin/bash -e {0}
> env:
> pythonLocation: /opt/hostedtoolcache/Python/3.8.8/x64
> LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.8/x64/lib
> QYWX_CORPID: ***
> QYWX_CORPSECRET: ***
> QYWX_AGENTID: ***
> PJ_COOKIE: ***
> CSDN_COOKIE: ***
> TYYP_USERNAME:
> TYYP_PSW: ***
> TOOLLU_COOKIE: ***
> Traceback (most recent call last):
> File "index.py", line 44, in
> notify.send(toollu_msg)
> TypeError: send() missing 1 required positional argument: 'text'
> Error: Process completed with exit code 1.

嗯，出错了，最后一行  notify.send(toollu_msg)少了一个参数toollu_msg前面加个'tool.lu签到信息'
