### ISSUE TITLE
52的签到不起作用

### ISSUE THREAD

**Issue by Nshandeshu** [lqkxs3608/daily_signin#2]
这是出错的流程.github/workflows/main.yml at fa82c4c

name: daily_signin
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  20 11,23 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 安装环境
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 日常签到
      run: |
        python3 index.py
      env:
        QYWX_CORPID: ${{ secrets.QYWX_CORPID }}
        QYWX_CORPSECRET: ${{ secrets.QYWX_CORPSECRET }}
        QYWX_AGENTID: ${{ secrets.QYWX_AGENTID }}
        PJ_COOKIE: ${{ secrets.PJ_COOKIE }}
        CSDN_COOKIE: ${{ secrets.CSDN_COOKIE }}
        TYYP_USERNAME: ${{ secrets.TYYP_USERNAME }}
        TYYP_PSW: ${{ secrets.TYYP_PSW }}
        TOOLLU_COOKIE: ${{ secrets.TOOLLU_COOKIE }}

**Comment by lqkxs3608** [comment]
我这边能签上到，但是发的消息是空白，本地运行却没问题，正在找原因

**Comment by lqkxs3608** [comment]
经过调试，目前工作正常
